apiVersion: v1
kind: PersistentVolume
metadata:
  name: cadre-query-results
spec:
  capacity:
    storage: 123Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-3d097f44.efs.us-east-2.amazonaws.com
    path: "/"
